[build-system]
requires = ["setuptools>=61.0", "wheel", "twine"]
build-backend = "setuptools.build_meta"

[project]
name = "consenrich"
version = "0.0.1b0"
description = "Genome-wide extraction of reproducible continuous-valued signals hidden in noisy multisample functional genomics data"
readme = "README.md"
requires-python = ">=3.9"
authors = [
    {name = "Nolan H. Hamilton", email = "nolan.hamilton@unc.edu"},
    {name = "Benjamin D. McMichael", email = "bdmcmi@ad.unc.edu"},
    {name = "Michael I. Love", email = "milove@email.unc.edu"},
    {name = "Terrence S. Furey", email = "tsfurey@email.unc.edu"},
]
license = {text = "MIT"}

keywords = [
    "genomics",
    "functional genomics",
    "epigenomics",
    "epigenetics",
    "signal processing",
    "data fusion",
    "state estimator",
    "filter"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]

dependencies = [
    "numpy>=1.23",
    "scipy>=1.11",
    "pandas",
    "pysam",
    "pybedtools",
    "deeptools",
    "pyBigWig"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "sphinx",
    "twine"
]

[project.scripts]
consenrich = "consenrich.consenrich:main"

[tool.setuptools.packages.find]
where = ["consenrich"]

[tool.setuptools]
package-dir = {"" = "consenrich"}
include-package-data = true

[tool.setuptools.package-data]
"consenrich" = ["refdata/*"]
