# -*- coding: utf-8 -*-
r"""Various constants and genome resources used in Consenrich."""

import logging
import os
from typing import Final, TypeAlias

from numpy import float32 as _float32
from numpy import log as np_log

ConfigurationDefaultValue: TypeAlias = bool | int | float | str | tuple[str, ...] | None
ConfigurationProfileMap: TypeAlias = dict[str, dict[str, ConfigurationDefaultValue]]
GenomeEffectiveSizeMap: TypeAlias = dict[str, dict[int, int]]
StrTuple: TypeAlias = tuple[str, ...]
FloatTuple: TypeAlias = tuple[float, ...]

logger: Final[logging.Logger] = logging.getLogger(__name__)

ALIGNMENT_SOURCE_KINDS: Final[StrTuple] = ("BAM",)
FRAGMENTS_SOURCE_KIND: Final[str] = "FRAGMENTS"  # 10x
BEDGRAPH_SOURCE_KIND: Final[str] = "BEDGRAPH"
SUPPORTED_SOURCE_KINDS: Final[StrTuple] = ALIGNMENT_SOURCE_KINDS + (
    FRAGMENTS_SOURCE_KIND,
    BEDGRAPH_SOURCE_KIND,
)
SUPPORTED_BAM_INPUT_MODES: Final[StrTuple] = ("auto", "fragments", "reads", "read1")
SUPPORTED_FRAGMENT_POSITION_MODES: Final[StrTuple] = (
    "insertionendpoints",
    "fragmentendpoints",
)
SUPPORTED_COUNT_MODES: Final[StrTuple] = (
    "coverage",
    "cutsite",
    "fiveprime",
    "ffp",
    "ffp-center",
    "center",
    "midpoint",
    "conservedFractionalOverlap",
)
COUNT_MODE_CONSERVED_FRACTIONAL_OVERLAP: Final[str] = "conservedFractionalOverlap"
COUNT_MODE_COVERAGE: Final[str] = "coverage"
COUNT_MODE_CUTSITE: Final[str] = "cutsite"
EXPERIMENT_DEFAULT_NAME: Final[str] = "consenrichExperiment"

INPUT_DEFAULT_SAMPLES: Final[None] = None
INPUT_DEFAULT_BAM_FILES: Final[StrTuple] = ()
INPUT_DEFAULT_BAM_FILES_CONTROL: Final[StrTuple] = ()
INPUT_DEFAULT_ROLE: Final[str] = "treatment"

SAM_DEFAULT_THREADS: Final[int] = 1
SAM_DEFAULT_FLAG_EXCLUDE: Final[int] = 3844
SAM_DEFAULT_MIN_MAPPING_QUALITY: Final[int] = 20
SAM_DEFAULT_ONE_READ_PER_BIN: Final[int] = 0
SAM_DEFAULT_CHUNK_SIZE: Final[int] = 500_000
SAM_DEFAULT_BAM_INPUT_MODE: Final[str] = "auto"
SAM_DEFAULT_COUNT_MODE: Final[str] = COUNT_MODE_CONSERVED_FRACTIONAL_OVERLAP
SAM_DEFAULT_SHIFT_FORWARD_5P: Final[int] = 0
SAM_DEFAULT_SHIFT_REVERSE_5P: Final[int] = 0
SAM_DEFAULT_EXTEND_FROM_5P_BP: Final[int | None] = None
SAM_DEFAULT_MAX_INSERT_SIZE: Final[int] = 1000
SAM_DEFAULT_INFER_FRAGMENT_LENGTH: Final[int | None] = None
SAM_DEFAULT_MIN_TEMPLATE_LENGTH: Final[int] = -1

COUNTING_DEFAULT_INTERVAL_SIZE_BP: Final[int] = 50
COUNTING_DEFAULT_BACKGROUND_BLOCK_SIZE_BP: Final[int] = -1
COUNTING_DEFAULT_SCALE_FACTORS: Final[tuple[float, ...] | None] = None
COUNTING_DEFAULT_SCALE_FACTORS_CONTROL: Final[tuple[float, ...] | None] = None
COUNTING_DEFAULT_NORM_METHOD: Final[str] = "EGS"
COUNTING_DEFAULT_FRAGMENTS_GROUP_NORM: Final[str] = "NONE"
COUNTING_SUPPORTED_NORM_METHODS: Final[StrTuple] = ("EGS", "RPGC", "RPKM", "CPM", "SF")
COUNTING_SUPPORTED_FRAGMENTS_GROUP_NORMS: Final[StrTuple] = ("NONE", "CELLS")
COUNTING_DEFAULT_FIX_CONTROL: Final[bool] = False
COUNTING_DEFAULT_LOG_OFFSET: Final[float] = 1.0
COUNTING_DEFAULT_LOG_MULT: Final[float] = 1.0 / np_log(2.0)
COUNTING_DEFAULT_TRANSFORM_METHOD: Final[str] = "log"
COUNTING_DEFAULT_TRANSFORM_INPUT_OFFSET: Final[float | None] = None
COUNTING_DEFAULT_TRANSFORM_INPUT_SCALE: Final[float] = 1.0
COUNTING_DEFAULT_TRANSFORM_OUTPUT_SCALE: Final[float | None] = None
COUNTING_DEFAULT_TRANSFORM_OUTPUT_OFFSET: Final[float] = 0.0
COUNTING_DEFAULT_TRANSFORM_SHAPE: Final[float] = 1.0
COUNTING_ANSCOMBE_INPUT_OFFSET: Final[float] = 0.375
COUNTING_ANSCOMBE_OUTPUT_SCALE: Final[float] = 2.0
COUNTING_SUPPORTED_TRANSFORM_METHODS: Final[StrTuple] = (
    "log",
    "sqrt",
    "anscombe",
    "asinh",
    "asinhSqrt",
    "generalizedLog",
    "identity",
)
COUNTING_DEFAULT_CENTER_MB: Final[bool] = True
COUNTING_CENTER_MB_METHOD_MEDFILT: Final[str] = "medfilt"
COUNTING_CENTER_MB_METHOD_SAVGOL: Final[str] = "savgol"
COUNTING_SUPPORTED_CENTER_MB_METHODS: Final[StrTuple] = (
    COUNTING_CENTER_MB_METHOD_MEDFILT,
    COUNTING_CENTER_MB_METHOD_SAVGOL,
)
COUNTING_DEFAULT_CENTER_MB_METHOD: Final[str] = COUNTING_CENTER_MB_METHOD_MEDFILT

SC_DEFAULT_BARCODE_TAG: Final[str] = "CB"
SC_DEFAULT_COUNT_MODE: Final[str] = COUNT_MODE_CONSERVED_FRACTIONAL_OVERLAP
SC_DEFAULT_FRAGMENTS_GROUP_NORM: Final[str] = COUNTING_DEFAULT_FRAGMENTS_GROUP_NORM
SC_DEFAULT_FRAGMENT_POSITION_MODE: Final[str] = "insertionEndpoints"
SC_SUPPORTED_COUNT_MODES: Final[StrTuple] = (
    "coverage",
    "cutsite",
    "fiveprime",
    "center",
    "midpoint",
    COUNT_MODE_CONSERVED_FRACTIONAL_OVERLAP,
)

GENERIC_DEFAULT_CONFIGURATION: Final[str] = "generic"
SUPPORTED_DEFAULT_CONFIGURATIONS: Final[StrTuple] = (GENERIC_DEFAULT_CONFIGURATION,)
DEFAULT_CONFIGURATION_KEYS: Final[StrTuple] = ("configuration",)

GENOME_DEFAULT_NAME: Final[str | None] = None
GENOME_DEFAULT_CHROM_SIZES_FILE: Final[str | None] = None
GENOME_DEFAULT_BLACKLIST_FILE: Final[str | None] = None
GENOME_DEFAULT_SPARSE_BED_FILE: Final[str | None] = None
GENOME_DEFAULT_COVARIATE_CACHE_DIR: Final[str | None] = None
GENOME_DEFAULT_CHROMOSOMES: Final[StrTuple | None] = None
GENOME_DEFAULT_EXCLUDE_CHROMS: Final[StrTuple] = ()
GENOME_DEFAULT_EXCLUDE_FOR_NORM: Final[StrTuple] = ()
NONSTANDARD_CHROMOSOME_NAMES: Final[StrTuple] = (
    "chrY",
    "chrM",
    "chrMT",
    "M",
    "MT",
    "_",
)

STATE_MODEL_LEVEL: Final[str] = "level"
STATE_MODEL_LEVEL_TREND: Final[str] = "levelTrend"
STATE_MODEL_MODES: Final[StrTuple] = (
    STATE_MODEL_LEVEL,
    STATE_MODEL_LEVEL_TREND,
)
STATE_DEFAULT_INIT: Final[float] = 0.0
STATE_DEFAULT_COVAR_INIT: Final[float] = 1000.0
STATE_DEFAULT_BOUND_STATE: Final[bool] = False
STATE_DEFAULT_LOWER_BOUND: Final[float] = 0.0
STATE_DEFAULT_UPPER_BOUND: Final[float] = 10000.0

PROCESS_DEFAULT_DELTA_F: Final[float] = 1.0
PROCESS_DEFAULT_MIN_Q: Final[float] = 1.0e-6
PROCESS_DEFAULT_MAX_Q: Final[float] = 1000.0
PROCESS_DEFAULT_Q_PRIOR_LEVEL: Final[float] = 1.0e-3
PROCESS_DEFAULT_Q_PRIOR_TREND: Final[float] = 1.0e-3
PROCESS_DEFAULT_Q_SEED_PRIOR_LEVEL: Final[float] = PROCESS_DEFAULT_Q_PRIOR_LEVEL
PROCESS_DEFAULT_PRECISION_MULTIPLIER_MIN: Final[float] = (
    5.0e-3  # if < 0, triggers smallest convexity-preserving bound
)
PROCESS_DEFAULT_PRECISION_MULTIPLIER_MAX: Final[float] = 5.0e3
PROCESS_DEFAULT_STATE_MODEL: Final[str] = STATE_MODEL_LEVEL_TREND
PROCESS_NOISE_CALIBRATION_PUNC: Final[str] = "punc"
PROCESS_NOISE_CALIBRATION_SEED: Final[str] = "seed"
PROCESS_NOISE_CALIBRATION_FIXED_DIAGONAL: Final[str] = "fixedDiagonal"
PROCESS_NOISE_CALIBRATION_FIXED: Final[str] = "fixed"
PROCESS_NOISE_CALIBRATION_MODES: Final[StrTuple] = (
    PROCESS_NOISE_CALIBRATION_PUNC,
    PROCESS_NOISE_CALIBRATION_SEED,
    PROCESS_NOISE_CALIBRATION_FIXED_DIAGONAL,
    PROCESS_NOISE_CALIBRATION_FIXED,
)
EB_PRIOR_STRENGTH_WINSOR_TAIL: Final[float] = 0.01
PROCESS_DEFAULT_NOISE_CALIBRATION: Final[str] = PROCESS_NOISE_CALIBRATION_PUNC
PROCESS_DEFAULT_PUNC_LOCAL_WINDOW_MULTIPLIER: Final[float] = 1.0
PROCESS_DEFAULT_PUNC_DEPENDENCE_MULTIPLIER: Final[float] = 1.0
PROCESS_DEFAULT_PUNC_MIN_SCALE: Final[float] = 0.001
PROCESS_DEFAULT_PUNC_MAX_SCALE: Final[float] = 1000.0
PROCESS_DEFAULT_PUNC_MIN_WINDOW_WEIGHT: Final[float] = 2.0
PROCESS_DEFAULT_PUNC_PRIOR_RIDGE: Final[float] = 1.0e-2
PROCESS_DEFAULT_PUNC_PRIOR_DF: Final[float] = 4.0
PROCESS_DEFAULT_PUNC_PRIOR_DF_MOMENTS_MIN_WINDOWS: Final[int] = 16
PROCESS_DEFAULT_PUNC_PRIOR_DF_MOMENTS_WINSOR_TAIL: Final[float] = (
    EB_PRIOR_STRENGTH_WINSOR_TAIL
)
PROCESS_DEFAULT_PUNC_LEVEL_BUFFER_Z: Final[float] = 1.64
PROCESS_DEFAULT_PUNC_DEADBAND_PRIOR_WEIGHT: Final[float] = 0.99
PROCESS_DEFAULT_PUNC_USE_RELIABILITY_WEIGHTED_WINDOWS: Final[bool] = False
PROCESS_DEFAULT_PUNC_USE_WARMUP_FIT: Final[bool] = True
PROCESS_DEFAULT_PUNC_USE_TRANSITION_EVIDENCE: Final[bool] = True
PROCESS_DEFAULT_PUNC_USE_SCALE_REBASE: Final[bool] = True
PROCESS_DEFAULT_PUNC_USE_GLOBAL_SCALE: Final[bool] = True
PROCESS_DEFAULT_PUNC_USE_BOUNDARY_CLAMPS: Final[bool] = True
PROCESS_DEFAULT_PUNC_USE_PRIOR_DF_MOMENTS: Final[bool] = True
PROCESS_DEFAULT_PUNC_USE_PRIOR_SHRINKAGE: Final[bool] = True
PROCESS_DEFAULT_PUNC_TREND_SEED_RATIO: Final[float] = 1.0
PUNC_COVARIATES_MODE_TRANSITION: Final[str] = "transition"
PUNC_SUPPORTED_COVARIATE_MODES: Final[StrTuple] = (PUNC_COVARIATES_MODE_TRANSITION,)
PUNC_COVARIATE_FEATURES: Final[StrTuple] = ()
PROCESS_DEFAULT_PUNC_COVARIATES_ENABLED: Final[bool] = False
PROCESS_DEFAULT_PUNC_COVARIATES_MODE: Final[str] = PUNC_COVARIATES_MODE_TRANSITION
PROCESS_DEFAULT_PUNC_COVARIATE_FEATURES: Final[StrTuple] = PUNC_COVARIATE_FEATURES
PROCESS_DEFAULT_WARMUP_ECM_ITERS: Final[int] = 50
PROCESS_DEFAULT_WARMUP_OUTER_PASSES: Final[int] = 3

OBSERVATION_DEFAULT_MIN_R: Final[float] = 0.0
OBSERVATION_DEFAULT_MAX_R: Final[float] = 1000.0
OBSERVATION_DEFAULT_SAMPLING_ITERS: Final[int] = 10_000
MUNC_VARIANCE_MODEL_KALMAN: Final[str] = "kalman"
MUNC_VARIANCE_MODEL_CODE_KALMAN: Final[int] = 0
MUNC_SUPPORTED_VARIANCE_MODELS: Final[StrTuple] = (MUNC_VARIANCE_MODEL_KALMAN,)
OBSERVATION_DEFAULT_MUNC_VARIANCE_MODEL: Final[str] = MUNC_VARIANCE_MODEL_KALMAN
OBSERVATION_DEFAULT_MUNC_TREND_BLOCK_SIZE_BP: Final[int | None] = None
OBSERVATION_DEFAULT_MUNC_LOCAL_WINDOW_SIZE_BP: Final[int | None] = None
OBSERVATION_DEPENDENCE_MIN_CONTEXT_FLOOR_BP: Final[int] = 2500
OBSERVATION_DEFAULT_MUNC_DEPENDENCE_MIN_CONTEXT_SIZE_BP: Final[int] = (
    OBSERVATION_DEPENDENCE_MIN_CONTEXT_FLOOR_BP
)
OBSERVATION_DEPENDENCE_MAX_CONTEXT_CEILING_BP: Final[int] = 100_000
OBSERVATION_DEFAULT_DEPENDENCE_MAX_CONTEXT_SIZE_BP: Final[int] = (
    OBSERVATION_DEPENDENCE_MAX_CONTEXT_CEILING_BP
)
OBSERVATION_DEFAULT_DEPENDENCE_NUM_BLOCKS: Final[int] = 5000
OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_MEDIAN_BP: Final[float] = 50_000
OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_SIGMA: Final[float] = 1.0
OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_MIN_BP: Final[int] = 5_000
OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_MAX_BP: Final[int] = 100_000
OBSERVATION_DEFAULT_DEPENDENCE_PRIOR_MEDIAN_SPAN: Final[float | None] = None
OBSERVATION_DEFAULT_DEPENDENCE_PRIOR_LOG_SD: Final[float] = 1.0
OBSERVATION_DEFAULT_DEPENDENCE_ACF_POINT_THRESHOLD: Final[float] = 0.1
OBSERVATION_DEFAULT_DEPENDENCE_ACF_REQUIRED_CROSSINGS: Final[int] = 5
OBSERVATION_DEFAULT_DEPENDENCE_ACF_MIN_EVIDENCE_NATS: Final[float] = 250.0
OBSERVATION_DEFAULT_MUNC_TREND_BLOCK_DEPENDENCE_MULTIPLIER: Final[float] = 2.0
OBSERVATION_DEFAULT_MUNC_LOCAL_WINDOW_DEPENDENCE_MULTIPLIER: Final[float] = 2.0
OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_ENABLED: Final[bool] = True
OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_PASSES: Final[int] = 3
OBSERVATION_MIN_MUNC_SEED_WEIGHT_PASSES: Final[int] = 2
OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_MIN: Final[float] = 0.001
OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_MAX: Final[float] = 1000.0
OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_STUDENT_T: Final[bool] = True
OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_STUDENT_TDF: Final[float] = 8.0
OBSERVATION_DEFAULT_MUNC_SEED_PROCESS_MIN_Q: Final[float] = PROCESS_DEFAULT_MIN_Q
OBSERVATION_DEFAULT_MUNC_SEED_PROCESS_MAX_Q: Final[float] = PROCESS_DEFAULT_MAX_Q
OBSERVATION_MUNC_SEED_WEIGHT_CONFIG_KEYS: Final[StrTuple] = (
    "observationParams.muncSeedWeight.enabled",
    "observationParams.muncSeedWeight.passes",
    "observationParams.muncSeedWeight.min",
    "observationParams.muncSeedWeight.max",
    "observationParams.muncSeedWeight.studentT",
    "observationParams.muncSeedWeight.studentTdf",
)
OBSERVATION_MUNC_SEED_WEIGHT_LOG_FIELDS: Final[StrTuple] = (
    "muncSeedWeightEnabled",
    "muncSeedWeightPasses",
    "muncSeedWeightMin",
    "muncSeedWeightMax",
    "muncSeedWeightStudentT",
    "muncSeedWeightStudentTdf",
)
OBSERVATION_MUNC_SEED_PROCESS_CONFIG_KEYS: Final[StrTuple] = (
    "observationParams.muncSeedProcess.minQ",
    "observationParams.muncSeedProcess.maxQ",
)
OBSERVATION_MUNC_SEED_PROCESS_LOG_FIELDS: Final[StrTuple] = (
    "muncSeedProcessMinQ",
    "muncSeedProcessMaxQ",
)
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_TILE_SIZE_BP: Final[int | None] = None
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_TILE_COUNT: Final[int] = 1024
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_STRATA: Final[int | None] = None
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_MIN_TILES_PER_STRATUM: Final[int] = 10
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_SEED: Final[int] = 42
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_SUPPORT_MIN_Q: Final[float] = 0.01
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_SUPPORT_MAX_Q: Final[float] = 0.99
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_MAX_EXTRAPOLATED_FRACTION: Final[float] = 0.10
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_WARMUP_ECM_ITERS: Final[int] = 50
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_WARMUP_OUTER_PASSES: Final[int] = 3
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_STRENGTH_WINSOR_TAIL: Final[float] = (
    EB_PRIOR_STRENGTH_WINSOR_TAIL
)
MUNC_EB_PRIOR_G_UNCERTAINTY_MODE_PROXY: Final[str] = "proxy"  # diagonal approximation
MUNC_EB_PRIOR_G_UNCERTAINTY_MODE_DISABLED: Final[str] = "disabled"
MUNC_SUPPORTED_EB_PRIOR_G_UNCERTAINTY_MODES: Final[StrTuple] = (
    MUNC_EB_PRIOR_G_UNCERTAINTY_MODE_PROXY,
    MUNC_EB_PRIOR_G_UNCERTAINTY_MODE_DISABLED,
)
OBSERVATION_DEFAULT_MUNC_EB_PRIOR_G_UNCERTAINTY_MODE: Final[str] = (
    MUNC_EB_PRIOR_G_UNCERTAINTY_MODE_PROXY
)
OBSERVATION_DEFAULT_USE_COUNT_NOISE_FLOOR: Final[bool] = True
OBSERVATION_DEFAULT_EB_USE: Final[bool] = True
OBSERVATION_DEFAULT_EB_SET_NU0: Final[float | None] = None
OBSERVATION_DEFAULT_EB_SET_NUL: Final[float | None] = None
OBSERVATION_DEFAULT_TREND_NUM_BASIS: Final[int] = 25
OBSERVATION_DEFAULT_TREND_MIN_OBS_PER_BASIS: Final[float] = 50.0
OBSERVATION_DEFAULT_TREND_MIN_EDF: Final[float] = 2.0
OBSERVATION_DEFAULT_TREND_MAX_EDF: Final[float] = 10.0
OBSERVATION_DEFAULT_TREND_LAMBDA_MIN: Final[float] = 1.0e-6
OBSERVATION_DEFAULT_TREND_LAMBDA_MAX: Final[float] = 1.0e6
OBSERVATION_DEFAULT_TREND_LAMBDA_GRID_SIZE: Final[int] = 101
OBSERVATION_DEFAULT_NUM_NEAREST: Final[int] = 0
OBSERVATION_DEFAULT_RESTRICT_LOCAL_VARIANCE_TO_SPARSE_BED: Final[bool] = False
OBSERVATION_DEFAULT_SPARSE_SUPPORT_SCALE_BP: Final[float] = -1.0
OBSERVATION_DEFAULT_SPARSE_SUPPORT_PRIOR: Final[float] = 1.0
OBSERVATION_DEFAULT_PAD: Final[float] = 1.0e-4
OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MIN: Final[float] = 1.0
OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MAX: Final[float] = 1.0
OBSERVATION_DEFAULT_USE_REPLICATE_TRENDS: Final[bool] = False
MUNC_COVARIATES_MODE_PER_REPLICATE_ADDITIVE: Final[str] = "perReplicateAdditive"
MUNC_SUPPORTED_COVARIATE_MODES: Final[StrTuple] = (
    MUNC_COVARIATES_MODE_PER_REPLICATE_ADDITIVE,
)
MUNC_COVARIATE_FEATURES: Final[StrTuple] = (
    "gc",
    "low_mappability_frac",
    "repeat_frac",
)
OBSERVATION_DEFAULT_MUNC_COVARIATES_ENABLED: Final[bool] = False
OBSERVATION_DEFAULT_MUNC_COVARIATES_MODE: Final[str] = (
    MUNC_COVARIATES_MODE_PER_REPLICATE_ADDITIVE
)
OBSERVATION_DEFAULT_MUNC_COVARIATE_FEATURES: Final[StrTuple] = MUNC_COVARIATE_FEATURES

FIT_DEFAULT_FIXED_BACKGROUND_ITERS: Final[int] = 50
FIT_DEFAULT_FIXED_BACKGROUND_RTOL: Final[float] = 1.0e-6
FIT_DEFAULT_T_INNER_ITERS: Final[int] = 5
FIT_DEFAULT_ROBUST_T_NU: Final[float] = 8.0
FIT_DEFAULT_USE_OBS_PRECISION_REWEIGHTING: Final[bool] = False
FIT_DEFAULT_USE_PROCESS_PRECISION_REWEIGHTING: Final[bool] = True
FIT_DEFAULT_USE_APN: Final[bool] = False
FIT_DEFAULT_BACKGROUND: Final[bool] = True
FIT_DEFAULT_USE_NONNEGATIVE_BACKGROUND: Final[bool] = True
FIT_DEFAULT_BACKGROUND_NEGATIVE_PENALTY_MULTIPLIER: Final[float] = 2.0
FIT_DEFAULT_ZERO_CENTER_BACKGROUND: Final[bool] = False
FIT_DEFAULT_OUTER_ITERS: Final[int] = 32
FIT_DEFAULT_MIN_OUTER_ITERS: Final[int] = 3
FIT_DEFAULT_BACKGROUND_SHIFT_RTOL: Final[float] = 1.0e-2
FIT_DEFAULT_OUTER_NLL_RTOL: Final[float] = 1.0e-4
FIT_DEFAULT_BACKGROUND_SMOOTHNESS: Final[float] = 25.0
FIT_DEFAULT_BACKGROUND_LENGTH_SCALE_MULTIPLIER: Final[float] = 16.0

OUTPUT_DEFAULT_ROUND_DIGITS: Final[int] = 3
OUTPUT_DEFAULT_WRITE_UNCERTAINTY: Final[bool] = True
OUTPUT_STATE_SHRINKAGE_MODEL_ADAPTIVE_NORMAL_MIXTURE: Final[str] = (
    "adaptiveNormalMixture"
)
OUTPUT_STATE_SHRINKAGE_MODEL_SPIKE_AND_NORMAL: Final[str] = "spikeAndNormal"
OUTPUT_STATE_SHRINKAGE_MODEL_SPIKE_AND_STUDENT_T: Final[str] = "spikeAndStudentT"
OUTPUT_STATE_SHRINKAGE_MODELS: Final[StrTuple] = (
    OUTPUT_STATE_SHRINKAGE_MODEL_ADAPTIVE_NORMAL_MIXTURE,
    OUTPUT_STATE_SHRINKAGE_MODEL_SPIKE_AND_NORMAL,
    OUTPUT_STATE_SHRINKAGE_MODEL_SPIKE_AND_STUDENT_T,
)
OUTPUT_DEFAULT_WRITE_STATE_SHRINKAGE: Final[bool] = True
OUTPUT_DEFAULT_STATE_SHRINKAGE_MODEL: Final[str] = (
    OUTPUT_STATE_SHRINKAGE_MODEL_SPIKE_AND_STUDENT_T
)
OUTPUT_DEFAULT_STATE_SHRINKAGE_PRIOR_SPIKE_PROP: Final[float | None] = None
OUTPUT_DEFAULT_STATE_SHRINKAGE_PRIOR_SCALE: Final[float | None] = None
OUTPUT_DEFAULT_STATE_SHRINKAGE_SPIKE_PSEUDO_COUNT: Final[float | None] = None
OUTPUT_DEFAULT_STATE_SHRINKAGE_SPIKE_PSEUDO_COUNT_FRACTION: Final[float] = 0.1
OUTPUT_DEFAULT_STATE_SHRINKAGE_SPIKE_PSEUDO_COUNT_MIN: Final[float] = 1.0e-6
OUTPUT_DEFAULT_STATE_SHRINKAGE_SPIKE_PSEUDO_COUNT_MAX: Final[float] = 1.0e6
OUTPUT_DEFAULT_STATE_SHRINKAGE_SCALE_ANCHOR_WEIGHT: Final[float | None] = None
OUTPUT_DEFAULT_STATE_SHRINKAGE_SCALE_ANCHOR_WEIGHT_FRACTION: Final[float] = 0.05
OUTPUT_DEFAULT_STATE_SHRINKAGE_SCALE_ANCHOR_WEIGHT_MIN: Final[float] = 25.0
OUTPUT_DEFAULT_STATE_SHRINKAGE_STUDENT_T_DF: Final[float] = 1.0
OUTPUT_DEFAULT_STATE_SHRINKAGE_STUDENT_T_QUADRATURE_ORDER: Final[int] = 16
OUTPUT_DEFAULT_SAVE_BACKGROUND_TRACKS: Final[bool] = True
OUTPUT_DEFAULT_SAVE_GAINS: Final[bool] = True
OUTPUT_DEFAULT_PLOT_OPTIMIZATION_PATH: Final[bool] = True
OUTPUT_DEFAULT_PLOT_CORRELATION_LENGTH: Final[bool] = True
OUTPUT_DEFAULT_CUTOFF_REPORT: Final[bool] = False
OUTPUT_DEFAULT_WRITE_RUN_SUMMARY: Final[bool] = True
OUTPUT_PRECISION_DIAGNOSTIC_DETAILS: Final[StrTuple] = ("summary", "sampled", "full")
OUTPUT_DEFAULT_PRECISION_DIAGNOSTIC_DETAIL: Final[str] = "summary"
OUTPUT_DEFAULT_MAX_PRECISION_DIAGNOSTIC_ROWS_PER_CHROMOSOME: Final[int] = 1_000
OUTPUT_DEFAULT_MAX_NON_TRACK_FILE_BYTES: Final[int] = 250 * 1024 * 1024
OUTPUT_DIAGNOSTIC_TRACK_NAMES: Final[StrTuple] = (
    "slope",
    "preKappaQLevel",
    "preKappaQTrend",
    "effectiveQLevel",
    "effectiveQTrend",
    "puncQScale",
    "muncTrace",
    "sumGain0",
    "sumGain1",
)
OUTPUT_DEFAULT_DIAGNOSTIC_TRACKS: Final[StrTuple] = ()

LOGGING_VERBOSITY_LEVELS: Final[StrTuple] = ("quiet", "normal", "verbose", "debug")
LOGGING_DEFAULT_VERBOSITY: Final[str] = "normal"
LOGGING_PROGRESS_MODES: Final[StrTuple] = ("auto", "on", "off")
LOGGING_DEFAULT_PROGRESS: Final[str] = "auto"
LOGGING_DEFAULT_LOG_FILE: Final[str | None] = None

UNCERTAINTY_CALIBRATION_POSITIVE_FLOOR: Final[float] = 1.0e-12
UNCERTAINTY_CALIBRATION_FEATURE_POSITIVE_FLOOR: Final[float] = 1.0e-12
UNCERTAINTY_CALIBRATION_FEATURE_SCALE_FLOOR: Final[float] = 1.0e-8
UNCERTAINTY_CALIBRATION_FEATURE_MAD_NORMAL_SCALE: Final[float] = 1.4826
UNCERTAINTY_CALIBRATION_FEATURE_HIGH_SIGNAL_QUANTILE: Final[float] = 0.90
UNCERTAINTY_CALIBRATION_FEATURE_NAMES: Final[StrTuple] = (
    "intercept",
    "log_state_variance",
    "log_mean_observation_variance",
    "abs_state",
    "abs_state_delta",
    "high_signal",
)
UNCERTAINTY_CALIBRATION_AUTO_BLOCK_MIN_BP: Final[int] = 25_000
UNCERTAINTY_CALIBRATION_AUTO_BLOCK_INTERVAL_MULTIPLIER: Final[int] = 100
UNCERTAINTY_CALIBRATION_MIN_BLOCK_INTERVALS: Final[int] = 8
UNCERTAINTY_CALIBRATION_MIN_FOLDS: Final[int] = 2
UNCERTAINTY_CALIBRATION_MIN_CALIBRATION_ECM_ITERS: Final[int] = 50
UNCERTAINTY_CALIBRATION_DEFAULT_TARGETS: Final[FloatTuple] = (
    0.50,
    0.80,
    0.90,
    0.95,
)
UNCERTAINTY_CALIBRATION_TARGET_ALPHA_FLOOR: Final[float] = 1.0e-6
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MIN: Final[float] = 1.0
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MAX: Final[float] = 25.0
UNCERTAINTY_CALIBRATION_FACTOR_MIN_FLOOR: Final[float] = 1.0e-6
UNCERTAINTY_CALIBRATION_FACTOR_MAX_MIN_RATIO: Final[float] = 1.01
UNCERTAINTY_CALIBRATION_DEFAULT_RIDGE: Final[float] = 1.0e-2
UNCERTAINTY_CALIBRATION_SCORE_PSTATE_DECILES: Final[int] = 10
UNCERTAINTY_CALIBRATION_SCORE_SD_DECILES: Final[int] = (
    UNCERTAINTY_CALIBRATION_SCORE_PSTATE_DECILES
)
UNCERTAINTY_CALIBRATION_SCORE_STATE_ABS_QUANTILE: Final[float] = 0.90
UNCERTAINTY_CALIBRATION_SCORE_FOLD_CODE_STRIDE: Final[int] = 4096
UNCERTAINTY_CALIBRATION_SCORE_REPLICATE_CODE_STRIDE: Final[int] = 32
UNCERTAINTY_CALIBRATION_SUMMARY_MEDIAN_QUANTILE: Final[float] = 0.50
UNCERTAINTY_CALIBRATION_SUMMARY_Q90_QUANTILE: Final[float] = 0.90
UNCERTAINTY_CALIBRATION_DEFAULT_MAX_SCORES: Final[int] = 200_000
UNCERTAINTY_CALIBRATION_DEFAULT_MAX_DIAGNOSTIC_ROWS: Final[int] = 50_000
UNCERTAINTY_CALIBRATION_DEFAULT_MIN_HELDOUT_CELLS: Final[int] = 1_000
UNCERTAINTY_CALIBRATION_DEFAULT_SEED: Final[int] = 1729
UNCERTAINTY_CALIBRATION_DIAGNOSTIC_SEED_OFFSET: Final[int] = 10_000
UNCERTAINTY_CALIBRATION_MASKED_OBSERVATION_VARIANCE: Final[_float32] = _float32(1.0e30)
UNCERTAINTY_CALIBRATION_MODE_DELETE_BLOCK_STATE: Final[str] = "delete_block_state"
UNCERTAINTY_CALIBRATION_MODES: Final[StrTuple] = (
    UNCERTAINTY_CALIBRATION_MODE_DELETE_BLOCK_STATE,
)
UNCERTAINTY_CALIBRATION_DEFAULT_MODE: Final[str] = (
    UNCERTAINTY_CALIBRATION_MODE_DELETE_BLOCK_STATE
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_HYBRID: Final[str] = "hybrid"
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_COVARIANCE_DIFFERENCE: Final[str] = (
    "covariance_difference"
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_HELDOUT_INFORMATION: Final[str] = (
    "heldout_information"
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_MODES: Final[StrTuple] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_HYBRID,
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_COVARIANCE_DIFFERENCE,
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_HELDOUT_INFORMATION,
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_TARGET_STATE: Final[str] = "state"
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_TARGET_STATE_PLUS_BACKGROUND: Final[str] = (
    "state_plus_background"
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_TARGET_SIGNALS: Final[StrTuple] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_TARGET_STATE,
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_TARGET_STATE_PLUS_BACKGROUND,
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_FACTOR_GLOBAL: Final[str] = "global"
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_FACTOR_SEG_SHRINK: Final[str] = "segShrink"
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_FACTOR_MODELS: Final[StrTuple] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_FACTOR_GLOBAL,
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_FACTOR_SEG_SHRINK,
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_UNIFORM: Final[str] = "uniform"
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_INFORMATION_FRACTION: Final[str] = (
    "information_fraction"
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_SQRT_INFORMATION_FRACTION: Final[str] = (
    "sqrt_information_fraction"
)
UNCERTAINTY_CALIBRATION_DELETE_BLOCK_SCORE_WEIGHT_MODES: Final[StrTuple] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_UNIFORM,
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_INFORMATION_FRACTION,
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_SQRT_INFORMATION_FRACTION,
)
UNCERTAINTY_CALIBRATION_REFIT_PROCESS_NOISE_WARMUP_ECM_ITERS: Final[int] = (
    PROCESS_DEFAULT_WARMUP_ECM_ITERS
)
UNCERTAINTY_CALIBRATION_DEFAULT_ENABLED: Final[bool] = True
UNCERTAINTY_CALIBRATION_DEFAULT_FOLDS: Final[int] = 2
UNCERTAINTY_CALIBRATION_DEFAULT_BLOCK_SIZE_BP: Final[int | None] = None
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_DELETION_PROBABILITY: Final[float] = 0.25
UNCERTAINTY_CALIBRATION_DEFAULT_MAX_HELDOUT_CELLS: Final[int | None] = None
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MIN_OVERRIDE: Final[float | None] = None
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MAX_OVERRIDE: Final[float | None] = None
UNCERTAINTY_CALIBRATION_DEFAULT_CALIBRATION_ECM_ITERS: Final[int] = 50
UNCERTAINTY_CALIBRATION_DEFAULT_CALIBRATION_OUTER_ITERS: Final[int] = 2
UNCERTAINTY_CALIBRATION_DEFAULT_TARGET_CALIBRATION_DELTA: Final[float] = 0.5
UNCERTAINTY_CALIBRATION_DEFAULT_SCALE_UNCERTAINTY_BY_TARGET_CALIBRATION: Final[bool] = (
    False  # `True` is aggressive and scales for a PAC-like calibration
)
UNCERTAINTY_CALIBRATION_SCALE_UNCERTAINTY_BY_TARGET_CALIBRATION_CONFIG_KEY: Final[
    str
] = "uncertaintyCalibrationParams.scaleUncertaintyByTargetCalibration"
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_VARIANCE_MODE: Final[str] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_VARIANCE_HYBRID
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_USE_LAMBDA_IN_INFORMATION: Final[bool] = (
    False
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_TARGET_SIGNAL: Final[str] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_TARGET_STATE
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FACTOR_MODEL: Final[str] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_FACTOR_SEG_SHRINK
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FACTOR_SEGMENT_COUNT: Final[int] = 128  #
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FACTOR_BOOTSTRAP_REPLICATES: Final[int] = (
    100
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_MIN_INFORMATION_FRACTION: Final[float] = (
    1.0e-4
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_MAX_INFORMATION_FRACTION: Final[float] = (
    0.95
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_MIN_DELTA_VARIANCE: Final[float] = (
    UNCERTAINTY_CALIBRATION_POSITIVE_FLOOR
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_SCORE_WEIGHT_MODE: Final[str] = (
    UNCERTAINTY_CALIBRATION_DELETE_BLOCK_WEIGHT_INFORMATION_FRACTION
)
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FALLBACK_MIN_VALID_FRACTION: Final[
    float
] = 0.25
UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_APPLY_TARGET_CALIBRATION: Final[
    bool | None
] = None
UNCERTAINTY_CALIBRATION_DEFAULT_PAD: Final[float] = 1.0e-4
UNCERTAINTY_CALIBRATION_DEFAULT_WRITE_DIAGNOSTICS: Final[bool] = False

MATCHING_DEFAULT_ENABLED: Final[bool] = True
MATCHING_DEFAULT_RAND_SEED: Final[int] = 42
MATCHING_DEFAULT_NUM_BOOTSTRAP: Final[int] = 128
MATCHING_DEFAULT_THRESHOLD_Z: Final[float] = 2.0
MATCHING_DEFAULT_DEPENDENCE_SPAN: Final[int | None] = None
MATCHING_DEFAULT_GAMMA: Final[float] = 0.25
MATCHING_DEFAULT_SELECTION_PENALTY: Final[float | None] = None
MATCHING_DEFAULT_GAMMA_SCALE: Final[float] = 0.5
MATCHING_DEFAULT_NESTED_ROCCO_ITERS: Final[int] = 3
MATCHING_DEFAULT_NESTED_ROCCO_BUDGET_SCALE: Final[float] = 0.75
MATCHING_DEFAULT_EXPORT_FILTER_UNCERTAINTY_MULTIPLIER: Final[float] = 2.0
MATCHING_DEFAULT_MIN_PEAK_SCORE: Final[float | None] = 0.1
MATCHING_DEFAULT_USE_SHRUNK_STATE_SCORES: Final[bool] = True
MATCHING_PEAK_MODES: Final[StrTuple] = ("narrow", "broad", "both")
MATCHING_DEFAULT_PEAK_MODE: Final[str] = "both"
MATCHING_DEFAULT_BROAD_WEAK_THRESHOLD_Z: Final[float] = 1.2816
MATCHING_DEFAULT_BROAD_MAX_GAP_BP: Final[int | None] = None
MATCHING_DEFAULT_BROAD_MIN_PEAK_BP: Final[int] = 1000
MATCHING_DEFAULT_BROAD_PARENT_GAMMA_MULTIPLIER: Final[float] = 2.0
MATCHING_DEFAULT_BROAD_BRIDGE_DIP_PENALTY_FRACTION: Final[float] = 0.5
MATCHING_METADATA_DETAILS: Final[StrTuple] = ("compact", "full")
MATCHING_DEFAULT_METADATA_DETAIL: Final[str] = "compact"
MATCHING_SUPPORTED_UNCERTAINTY_SCORE_MODES: Final[StrTuple] = (
    "state",
    "lower_confidence",
)
MATCHING_DEFAULT_UNCERTAINTY_SCORE_MODE: Final[str] = "state"
MATCHING_DEFAULT_UNCERTAINTY_SCORE_Z: Final[float] = 1.0

ROCCO_BUDGET_MIN: Final[float] = 0.001
ROCCO_BUDGET_MAX: Final[float] = 0.25
ROCCO_NULL_QUANTILE: Final[float] = 0.9
ROCCO_THRESHOLD_Z_DEFAULT: Final[float] = MATCHING_DEFAULT_THRESHOLD_Z
ROCCO_NUM_BOOTSTRAP_DEFAULT: Final[int] = MATCHING_DEFAULT_NUM_BOOTSTRAP
ROCCO_BUDGET_Z_GRID: Final[FloatTuple] = (1.5, 2.0, 2.5, 3.0)
ROCCO_MAX_ITER_DEFAULT: Final[int] = 60
ROCCO_MIN_PEAK_BP: Final[int] = 200
NESTED_ROCCO_ITERS_DEFAULT: Final[int] = MATCHING_DEFAULT_NESTED_ROCCO_ITERS
NESTED_ROCCO_JACCARD_DEFAULT: Final[float] = 0.999
NESTED_ROCCO_MIN_PARENT_STEPS: Final[int] = 5
NESTED_ROCCO_MIN_CHILD_STEPS: Final[int] = NESTED_ROCCO_MIN_PARENT_STEPS
NESTED_ROCCO_BUDGET_SCALE_DEFAULT: Final[float] = (
    MATCHING_DEFAULT_NESTED_ROCCO_BUDGET_SCALE
)
NESTED_ROCCO_SUBTASK_MAX_ITER: Final[int] = 5
EXPORT_MEDIAN_SIGNAL_LOCAL_UNCERTAINTY_MULTIPLIER: Final[float] = (
    MATCHING_DEFAULT_EXPORT_FILTER_UNCERTAINTY_MULTIPLIER
)
MASSIVE_SUBPEAK_CLEANUP_DEFAULT: Final[bool] = True
MASSIVE_SUBPEAK_MIN_BP: Final[int] = 7500
MASSIVE_SUBPEAK_WIDTH_ALPHA: Final[float] = 0.1
MASSIVE_SUBPEAK_WIDTH_BULK_QUANTILE: Final[float] = 0.95
MASSIVE_SUBPEAK_MAX_FRACTION: Final[float] = 0.005
MASSIVE_SUBPEAK_MIN_LOG_GAP: Final[float] = 0.10
MASSIVE_SUBPEAK_MIN_PEAKS: Final[int] = 25
MASSIVE_SUBPEAK_SPLIT_QUANTILE: Final[float] = 0.25
MASSIVE_SUBPEAK_SPLIT_Z: Final[float] = 2.0
MASSIVE_SUBPEAK_MAX_DEPTH: Final[int] = 8
MASSIVE_SUBPEAK_MIN_CHILD_BP: Final[int] = 250
MASSIVE_SUBPEAK_MIN_CHILD_FRACTION: Final[float] = 0.05

DEFAULT_CONFIGURATION_VALUES: Final[ConfigurationProfileMap] = {
    GENERIC_DEFAULT_CONFIGURATION: {
        "fitParams.ECM_fixedBackgroundIters": FIT_DEFAULT_FIXED_BACKGROUND_ITERS,
        "fitParams.ECM_fixedBackgroundRtol": FIT_DEFAULT_FIXED_BACKGROUND_RTOL,
        "fitParams.t_innerIters": FIT_DEFAULT_T_INNER_ITERS,
        "fitParams.ECM_outerIters": FIT_DEFAULT_OUTER_ITERS,
        "fitParams.ECM_minOuterIters": FIT_DEFAULT_MIN_OUTER_ITERS,
        "fitParams.ECM_backgroundShiftRtol": FIT_DEFAULT_BACKGROUND_SHIFT_RTOL,
        "fitParams.ECM_outerNLLRtol": FIT_DEFAULT_OUTER_NLL_RTOL,
        "fitParams.ECM_backgroundSmoothness": FIT_DEFAULT_BACKGROUND_SMOOTHNESS,
        "fitParams.ECM_backgroundLengthScaleMultiplier": (
            FIT_DEFAULT_BACKGROUND_LENGTH_SCALE_MULTIPLIER
        ),
        "fitParams.useNonnegativeBackground": FIT_DEFAULT_USE_NONNEGATIVE_BACKGROUND,
        "fitParams.backgroundNegativePenaltyMultiplier": (
            FIT_DEFAULT_BACKGROUND_NEGATIVE_PENALTY_MULTIPLIER
        ),
        "processParams.processNoiseCalibration": PROCESS_DEFAULT_NOISE_CALIBRATION,
        "processParams.puncLocalWindowMultiplier": (
            PROCESS_DEFAULT_PUNC_LOCAL_WINDOW_MULTIPLIER
        ),
        "processParams.puncDependenceMultiplier": (
            PROCESS_DEFAULT_PUNC_DEPENDENCE_MULTIPLIER
        ),
        "processParams.puncMinScale": PROCESS_DEFAULT_PUNC_MIN_SCALE,
        "processParams.puncMaxScale": PROCESS_DEFAULT_PUNC_MAX_SCALE,
        "processParams.puncMinWindowWeight": PROCESS_DEFAULT_PUNC_MIN_WINDOW_WEIGHT,
        "processParams.puncPriorRidge": PROCESS_DEFAULT_PUNC_PRIOR_RIDGE,
        "processParams.puncPriorDf": PROCESS_DEFAULT_PUNC_PRIOR_DF,
        "processParams.puncLevelBufferZ": PROCESS_DEFAULT_PUNC_LEVEL_BUFFER_Z,
        "processParams.puncUseReliabilityWeightedWindows": (
            PROCESS_DEFAULT_PUNC_USE_RELIABILITY_WEIGHTED_WINDOWS
        ),
        "processParams.puncUseWarmupFit": PROCESS_DEFAULT_PUNC_USE_WARMUP_FIT,
        "processParams.puncUseTransitionEvidence": (
            PROCESS_DEFAULT_PUNC_USE_TRANSITION_EVIDENCE
        ),
        "processParams.puncUseScaleRebase": PROCESS_DEFAULT_PUNC_USE_SCALE_REBASE,
        "processParams.puncUseGlobalScale": PROCESS_DEFAULT_PUNC_USE_GLOBAL_SCALE,
        "processParams.puncUseBoundaryClamps": (
            PROCESS_DEFAULT_PUNC_USE_BOUNDARY_CLAMPS
        ),
        "processParams.puncUsePriorDfMoments": (
            PROCESS_DEFAULT_PUNC_USE_PRIOR_DF_MOMENTS
        ),
        "processParams.puncUsePriorShrinkage": (
            PROCESS_DEFAULT_PUNC_USE_PRIOR_SHRINKAGE
        ),
        "processParams.puncProcessCovariates.enabled": (
            PROCESS_DEFAULT_PUNC_COVARIATES_ENABLED
        ),
        "processParams.puncProcessCovariates.mode": (
            PROCESS_DEFAULT_PUNC_COVARIATES_MODE
        ),
        "processParams.puncProcessCovariates.features": (
            PROCESS_DEFAULT_PUNC_COVARIATE_FEATURES
        ),
        "processParams.processNoiseWarmupECMIters": PROCESS_DEFAULT_WARMUP_ECM_ITERS,
        "processParams.processNoiseWarmupOuterPasses": (
            PROCESS_DEFAULT_WARMUP_OUTER_PASSES
        ),
        "processParams.deltaF": PROCESS_DEFAULT_DELTA_F,
        "processParams.minQ": PROCESS_DEFAULT_MIN_Q,
        "processParams.maxQ": PROCESS_DEFAULT_MAX_Q,
        "processParams.qPriorLevel": PROCESS_DEFAULT_Q_PRIOR_LEVEL,
        "processParams.qPriorTrend": PROCESS_DEFAULT_Q_PRIOR_TREND,
        "processParams.qSeedPriorLevel": PROCESS_DEFAULT_Q_SEED_PRIOR_LEVEL,
        "processParams.stateModel": PROCESS_DEFAULT_STATE_MODEL,
        "processParams.precisionMultiplierMin": (
            PROCESS_DEFAULT_PRECISION_MULTIPLIER_MIN
        ),
        "processParams.precisionMultiplierMax": (
            PROCESS_DEFAULT_PRECISION_MULTIPLIER_MAX
        ),
        "genomeParams.genomeCovariateCacheDir": GENOME_DEFAULT_COVARIATE_CACHE_DIR,
        "observationParams.precisionMultiplierMin": (
            OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MIN
        ),
        "observationParams.precisionMultiplierMax": (
            OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MAX
        ),
        "observationParams.muncVarianceModel": (
            OBSERVATION_DEFAULT_MUNC_VARIANCE_MODEL
        ),
        "observationParams.muncTrendBlockSizeBP": (
            OBSERVATION_DEFAULT_MUNC_TREND_BLOCK_SIZE_BP
        ),
        "observationParams.muncLocalWindowSizeBP": (
            OBSERVATION_DEFAULT_MUNC_LOCAL_WINDOW_SIZE_BP
        ),
        "observationParams.muncDependenceMinContextSizeBP": (
            OBSERVATION_DEFAULT_MUNC_DEPENDENCE_MIN_CONTEXT_SIZE_BP
        ),
        "observationParams.dependenceMaxContextSizeBP": (
            OBSERVATION_DEFAULT_DEPENDENCE_MAX_CONTEXT_SIZE_BP
        ),
        "observationParams.dependenceNumBlocks": (
            OBSERVATION_DEFAULT_DEPENDENCE_NUM_BLOCKS
        ),
        "observationParams.dependenceBlockMedianBP": (
            OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_MEDIAN_BP
        ),
        "observationParams.dependenceBlockSigma": (
            OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_SIGMA
        ),
        "observationParams.dependenceBlockMinBP": (
            OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_MIN_BP
        ),
        "observationParams.dependenceBlockMaxBP": (
            OBSERVATION_DEFAULT_DEPENDENCE_BLOCK_MAX_BP
        ),
        "observationParams.dependencePriorMedianSpan": (
            OBSERVATION_DEFAULT_DEPENDENCE_PRIOR_MEDIAN_SPAN
        ),
        "observationParams.dependencePriorLogSd": (
            OBSERVATION_DEFAULT_DEPENDENCE_PRIOR_LOG_SD
        ),
        "observationParams.dependenceAcfPointThreshold": (
            OBSERVATION_DEFAULT_DEPENDENCE_ACF_POINT_THRESHOLD
        ),
        "observationParams.dependenceAcfRequiredCrossings": (
            OBSERVATION_DEFAULT_DEPENDENCE_ACF_REQUIRED_CROSSINGS
        ),
        "observationParams.dependenceAcfMinEvidenceNats": (
            OBSERVATION_DEFAULT_DEPENDENCE_ACF_MIN_EVIDENCE_NATS
        ),
        "observationParams.muncTrendBlockDependenceMultiplier": (
            OBSERVATION_DEFAULT_MUNC_TREND_BLOCK_DEPENDENCE_MULTIPLIER
        ),
        "observationParams.muncLocalWindowDependenceMultiplier": (
            OBSERVATION_DEFAULT_MUNC_LOCAL_WINDOW_DEPENDENCE_MULTIPLIER
        ),
        "observationParams.muncSeedWeight.enabled": (
            OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_ENABLED
        ),
        "observationParams.muncSeedWeight.passes": (
            OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_PASSES
        ),
        "observationParams.muncSeedWeight.min": (
            OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_MIN
        ),
        "observationParams.muncSeedWeight.max": (
            OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_MAX
        ),
        "observationParams.muncSeedWeight.studentT": (
            OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_STUDENT_T
        ),
        "observationParams.muncSeedWeight.studentTdf": (
            OBSERVATION_DEFAULT_MUNC_SEED_WEIGHT_STUDENT_TDF
        ),
        "observationParams.muncSeedProcess.minQ": (
            OBSERVATION_DEFAULT_MUNC_SEED_PROCESS_MIN_Q
        ),
        "observationParams.muncSeedProcess.maxQ": (
            OBSERVATION_DEFAULT_MUNC_SEED_PROCESS_MAX_Q
        ),
        "observationParams.muncEBPrior.tileSizeBP": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_TILE_SIZE_BP
        ),
        "observationParams.muncEBPrior.tileCount": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_TILE_COUNT
        ),
        "observationParams.muncEBPrior.strata": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_STRATA
        ),
        "observationParams.muncEBPrior.minTilesPerStratum": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_MIN_TILES_PER_STRATUM
        ),
        "observationParams.muncEBPrior.seed": OBSERVATION_DEFAULT_MUNC_EB_PRIOR_SEED,
        "observationParams.muncEBPrior.supportMinQ": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_SUPPORT_MIN_Q
        ),
        "observationParams.muncEBPrior.supportMaxQ": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_SUPPORT_MAX_Q
        ),
        "observationParams.muncEBPrior.maxExtrapolatedFraction": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_MAX_EXTRAPOLATED_FRACTION
        ),
        "observationParams.muncEBPrior.warmupECMIters": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_WARMUP_ECM_ITERS
        ),
        "observationParams.muncEBPrior.warmupOuterPasses": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_WARMUP_OUTER_PASSES
        ),
        "observationParams.muncEBPrior.gUncertaintyMode": (
            OBSERVATION_DEFAULT_MUNC_EB_PRIOR_G_UNCERTAINTY_MODE
        ),
        "observationParams.useCountNoiseFloor": (
            OBSERVATION_DEFAULT_USE_COUNT_NOISE_FLOOR
        ),
        "observationParams.muncCovariates.enabled": (
            OBSERVATION_DEFAULT_MUNC_COVARIATES_ENABLED
        ),
        "observationParams.muncCovariates.mode": (
            OBSERVATION_DEFAULT_MUNC_COVARIATES_MODE
        ),
        "observationParams.muncCovariates.features": (
            OBSERVATION_DEFAULT_MUNC_COVARIATE_FEATURES
        ),
        "observationParams.restrictLocalVarianceToSparseBed": (
            OBSERVATION_DEFAULT_RESTRICT_LOCAL_VARIANCE_TO_SPARSE_BED
        ),
        "countingParams.centerMB": COUNTING_DEFAULT_CENTER_MB,
        "countingParams.centerMBMethod": COUNTING_DEFAULT_CENTER_MB_METHOD,
        "outputParams.writeStateShrinkage": OUTPUT_DEFAULT_WRITE_STATE_SHRINKAGE,
        "outputParams.stateShrinkageModel": OUTPUT_DEFAULT_STATE_SHRINKAGE_MODEL,
        "outputParams.stateShrinkagePriorSpikeProp": (
            OUTPUT_DEFAULT_STATE_SHRINKAGE_PRIOR_SPIKE_PROP
        ),
        "outputParams.stateShrinkagePriorScale": OUTPUT_DEFAULT_STATE_SHRINKAGE_PRIOR_SCALE,
        "outputParams.stateShrinkageSpikePseudoCount": (
            OUTPUT_DEFAULT_STATE_SHRINKAGE_SPIKE_PSEUDO_COUNT
        ),
        "outputParams.stateShrinkageScaleAnchorWeight": (
            OUTPUT_DEFAULT_STATE_SHRINKAGE_SCALE_ANCHOR_WEIGHT
        ),
        "outputParams.stateShrinkageStudentTDF": (
            OUTPUT_DEFAULT_STATE_SHRINKAGE_STUDENT_T_DF
        ),
        "outputParams.stateShrinkageStudentTQuadratureOrder": (
            OUTPUT_DEFAULT_STATE_SHRINKAGE_STUDENT_T_QUADRATURE_ORDER
        ),
        "matchingParams.useShrunkStateScores": MATCHING_DEFAULT_USE_SHRUNK_STATE_SCORES,
        "matchingParams.peakMode": MATCHING_DEFAULT_PEAK_MODE,
        "matchingParams.broadWeakThresholdZ": MATCHING_DEFAULT_BROAD_WEAK_THRESHOLD_Z,
        "matchingParams.broadMaxGapBP": MATCHING_DEFAULT_BROAD_MAX_GAP_BP,
        "outputParams.saveBackgroundTracks": OUTPUT_DEFAULT_SAVE_BACKGROUND_TRACKS,
        "outputParams.saveGains": OUTPUT_DEFAULT_SAVE_GAINS,
        "outputParams.plotCorrelationLength": (
            OUTPUT_DEFAULT_PLOT_CORRELATION_LENGTH
        ),
        "outputParams.cutoffReport": OUTPUT_DEFAULT_CUTOFF_REPORT,
        "outputParams.writeRunSummary": OUTPUT_DEFAULT_WRITE_RUN_SUMMARY,
        "outputParams.precisionDiagnosticDetail": (
            OUTPUT_DEFAULT_PRECISION_DIAGNOSTIC_DETAIL
        ),
        "outputParams.maxPrecisionDiagnosticRowsPerChromosome": (
            OUTPUT_DEFAULT_MAX_PRECISION_DIAGNOSTIC_ROWS_PER_CHROMOSOME
        ),
        "outputParams.maxNonTrackFileBytes": OUTPUT_DEFAULT_MAX_NON_TRACK_FILE_BYTES,
        "loggingParams.verbosity": LOGGING_DEFAULT_VERBOSITY,
        "loggingParams.progress": LOGGING_DEFAULT_PROGRESS,
        "loggingParams.logFile": LOGGING_DEFAULT_LOG_FILE,
        "uncertaintyCalibrationParams.enabled": (
            UNCERTAINTY_CALIBRATION_DEFAULT_ENABLED
        ),
        "uncertaintyCalibrationParams.mode": UNCERTAINTY_CALIBRATION_DEFAULT_MODE,
        "uncertaintyCalibrationParams.deleteBlockVarianceMode": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_VARIANCE_MODE
        ),
        "uncertaintyCalibrationParams.deleteBlockUseLambdaInInformation": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_USE_LAMBDA_IN_INFORMATION
        ),
        "uncertaintyCalibrationParams.deleteBlockTargetSignal": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_TARGET_SIGNAL
        ),
        "uncertaintyCalibrationParams.deleteBlockFactorModel": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FACTOR_MODEL
        ),
        "uncertaintyCalibrationParams.deleteBlockFactorSegmentCount": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FACTOR_SEGMENT_COUNT
        ),
        "uncertaintyCalibrationParams.deleteBlockFactorBootstrapReplicates": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FACTOR_BOOTSTRAP_REPLICATES
        ),
        "uncertaintyCalibrationParams.deleteBlockDeletionProbability": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_DELETION_PROBABILITY
        ),
        "uncertaintyCalibrationParams.deleteBlockMinInformationFraction": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_MIN_INFORMATION_FRACTION
        ),
        "uncertaintyCalibrationParams.deleteBlockMaxInformationFraction": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_MAX_INFORMATION_FRACTION
        ),
        "uncertaintyCalibrationParams.deleteBlockMinDeltaVariance": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_MIN_DELTA_VARIANCE
        ),
        "uncertaintyCalibrationParams.deleteBlockFallbackMinValidFraction": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_FALLBACK_MIN_VALID_FRACTION
        ),
        "uncertaintyCalibrationParams.deleteBlockScoreWeightMode": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_SCORE_WEIGHT_MODE
        ),
        "uncertaintyCalibrationParams.calibrationOuterIters": (
            UNCERTAINTY_CALIBRATION_DEFAULT_CALIBRATION_OUTER_ITERS
        ),
        UNCERTAINTY_CALIBRATION_SCALE_UNCERTAINTY_BY_TARGET_CALIBRATION_CONFIG_KEY: (
            UNCERTAINTY_CALIBRATION_DEFAULT_SCALE_UNCERTAINTY_BY_TARGET_CALIBRATION
        ),
        "uncertaintyCalibrationParams.deleteBlockApplyTargetCalibration": (
            UNCERTAINTY_CALIBRATION_DEFAULT_DELETE_BLOCK_APPLY_TARGET_CALIBRATION
        ),
    }
}

EFFECTIVE_GENOME_SIZES: Final[GenomeEffectiveSizeMap] = {
    "hg19": {
        50: 2685511454,
        75: 2736124898,
        100: 2776919708,
        150: 2827436883,
        200: 2855463800,
        250: 2855044784,
    },
    "hg38": {
        50: 2701495711,
        75: 2747877702,
        100: 2805636231,
        150: 2862010428,
        200: 2887553103,
        250: 2898802627,
    },
    "t2t": {
        50: 2725240337,
        75: 2786136059,
        100: 2814334875,
        150: 2931551487,
        200: 2936403235,
        250: 2960856300,
    },
    "mm10": {
        50: 2308125299,
        75: 2407883243,
        100: 2467481008,
        150: 2494787038,
        200: 2520868989,
        250: 2538590322,
    },
    "mm39": {
        50: 2309746861,
        75: 2410055689,
        100: 2468088461,
        150: 2495461690,
        200: 2521902382,
        250: 2538633971,
    },
    "dm3": {
        50: 130428510,
        75: 135004387,
        100: 139647132,
        150: 144307658,
        200: 148523810,
        250: 151901455,
    },
    "dm6": {
        50: 125464678,
        75: 127324557,
        100: 129789773,
        150: 129940985,
        200: 132508963,
        250: 132900923,
    },
    "ce11": {
        50: 95159402,
        75: 96945370,
        100: 98259898,
        150: 98721103,
        200: 98672558,
        250: 101271756,
    },
}


def resolveGenomeName(genome: str) -> str:
    r"""Standardize the genome name for consistency
    :param genome: Name of the genome. See :class:`consenrich.core.genomeParams`.
    :type genome: str
    :return: Standardized genome name.
    :rtype: str
    :raises ValueError: If the genome is not recognized.
    """
    genome_ = genome.lower()
    if genome_ in ["hg19", "grch37"]:
        return "hg19"
    elif genome_ in ["hg38", "grch38"]:
        return "hg38"
    elif genome_ in ["t2t", "chm13", "t2t-chm13"]:
        return "t2t"
    elif genome_ in ["mm10", "grcm38"]:
        return "mm10"
    elif genome_ in ["mm39", "grcm39"]:
        return "mm39"
    elif genome_ in ["dm3"]:
        return "dm3"
    elif genome_ in ["dm6"]:
        return "dm6"
    elif genome_ in ["ce10", "ws220"]:
        return "ce10"
    elif genome_ in ["ce11", "wbcel235"]:
        return "ce11"
    raise ValueError(
        f"Genome {genome} is not recognized. Please provide a valid genome name or manually specify resources"
    )


def getEffectiveGenomeSize(genome: str, readLength: int) -> int:
    r"""Get the effective genome size for a given genome and read length.

    :param genome: Name of the genome. See :func:`consenrich.constants.resolveGenomeName` and :class:`consenrich.core.genomeParams`.
    :type genome: str
    :param readLength: Length of the reads. See :func:`consenrich.core.getReadLength`.
    :type readLength: int
    :raises ValueError: If the genome is not recognized or if the read length is not available for the genome.
    :return: Effective genome size in base pairs.
    :rtype: int
    """

    global EFFECTIVE_GENOME_SIZES
    genome_: str = resolveGenomeName(genome)
    if genome_ in EFFECTIVE_GENOME_SIZES:
        if readLength not in EFFECTIVE_GENOME_SIZES[genome_]:
            nearestReadLength: int = int(
                min(
                    EFFECTIVE_GENOME_SIZES[genome_].keys(),
                    key=lambda x: abs(x - readLength),
                )
            )
            return EFFECTIVE_GENOME_SIZES[genome_][nearestReadLength]
        return EFFECTIVE_GENOME_SIZES[genome_][readLength]
    raise ValueError(f"Defaults not available for {genome}")


def getGenomeResourceFile(genome: str, fileType: str, dir_: str = "data") -> str:
    r"""Get the path to a genome resource file.

    :param genome: the genome assembly. See :func:`consenrich.constants.resolveGenomeName` and :class:`consenrich.core.genomeParams`.
    :type genome: str
    :param fileType: One of 'sizes', 'blacklist', 'sparse'.
    :type fileType: str
    :return: Path to the resource file.
    :rtype: str
    :raises ValueError: If not a sizes, blacklist, or sparse file.
    :raises FileNotFoundError: If the resource file does not exist.
    """
    if fileType.lower() in ["sizes"]:
        fileName = f"{genome}.sizes"
    elif fileType.lower() in ["blacklist"]:
        fileName = f"{genome}_blacklist.bed"
    elif fileType.lower() in ["sparse"]:
        fileName = f"{genome}_sparse.bed"
    filePath = os.path.join(os.path.dirname(__file__), os.path.join(dir_, fileName))
    if not os.path.exists(filePath):
        raise FileNotFoundError(f"Resource file {filePath} does not exist.")
    return filePath
