# -*- coding: utf-8 -*-
r"""Various constants and genome resources used in Consenrich."""

import logging
import os
from typing import List, Optional

from numpy import float32 as _float32

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(module)s.%(funcName)s -  %(levelname)s - %(message)s",
)
logger = logging.getLogger(__name__)

ALIGNMENT_SOURCE_KINDS = ("BAM",)
FRAGMENTS_SOURCE_KIND = "FRAGMENTS"  # 10x
BEDGRAPH_SOURCE_KIND = "BEDGRAPH"
SUPPORTED_SOURCE_KINDS = ALIGNMENT_SOURCE_KINDS + (
    FRAGMENTS_SOURCE_KIND,
    BEDGRAPH_SOURCE_KIND,
)
SUPPORTED_BAM_INPUT_MODES = ("auto", "fragments", "reads", "read1")
SUPPORTED_FRAGMENT_POSITION_MODES = ("insertionendpoints", "fragmentendpoints")
SUPPORTED_COUNT_MODES = (
    "coverage",
    "cutsite",
    "fiveprime",
    "center",
)

GENERIC_DEFAULT_CONFIGURATION = "generic"
SUPPORTED_DEFAULT_CONFIGURATIONS = (GENERIC_DEFAULT_CONFIGURATION,)
DEFAULT_CONFIGURATION_KEYS = ("configuration",)

UNCERTAINTY_CALIBRATION_POSITIVE_FLOOR = 1.0e-12
UNCERTAINTY_CALIBRATION_FEATURE_POSITIVE_FLOOR = 1.0e-12
UNCERTAINTY_CALIBRATION_FEATURE_SCALE_FLOOR = 1.0e-8
UNCERTAINTY_CALIBRATION_FEATURE_MAD_NORMAL_SCALE = 1.4826
UNCERTAINTY_CALIBRATION_FEATURE_HIGH_SIGNAL_QUANTILE = 0.90
UNCERTAINTY_CALIBRATION_FEATURE_NAMES = (
    "intercept",
    "log_state_variance",
    "log_mean_observation_variance",
    "abs_state",
    "abs_state_delta",
    "high_signal",
)
UNCERTAINTY_CALIBRATION_AUTO_BLOCK_MIN_BP = 50_000
UNCERTAINTY_CALIBRATION_AUTO_BLOCK_INTERVAL_MULTIPLIER = 100
UNCERTAINTY_CALIBRATION_MIN_BLOCK_INTERVALS = 8
UNCERTAINTY_CALIBRATION_MIN_FOLDS = 2
UNCERTAINTY_CALIBRATION_MIN_HOLDOUT_REPLICATES = 1
UNCERTAINTY_CALIBRATION_DEFAULT_HOLDOUT_FRACTION_MIN = 0.10
UNCERTAINTY_CALIBRATION_DEFAULT_HOLDOUT_FRACTION_MAX = 0.30
UNCERTAINTY_CALIBRATION_MIN_CALIBRATION_ECM_ITERS = 2
UNCERTAINTY_CALIBRATION_DEFAULT_TARGETS = (0.50, 0.80, 0.90, 0.95)
UNCERTAINTY_CALIBRATION_TARGET_ALPHA_FLOOR = 1.0e-6
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MIN = 0.05
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MAX = 25.0
UNCERTAINTY_CALIBRATION_FACTOR_MIN_FLOOR = 1.0e-6
UNCERTAINTY_CALIBRATION_FACTOR_MAX_MIN_RATIO = 1.01
UNCERTAINTY_CALIBRATION_A_OBS_FACTOR_MIN = 0.25
UNCERTAINTY_CALIBRATION_A_OBS_FACTOR_MAX = 4.0
UNCERTAINTY_CALIBRATION_DEFAULT_RIDGE = 1.0e-2
UNCERTAINTY_CALIBRATION_DEFAULT_WIS_WEIGHT = 0.05
UNCERTAINTY_CALIBRATION_WIS_WEIGHT = UNCERTAINTY_CALIBRATION_DEFAULT_WIS_WEIGHT
UNCERTAINTY_CALIBRATION_DEFAULT_A_OBS_PENALTY = 1.0e-2
UNCERTAINTY_CALIBRATION_DEFAULT_A_OBS_PRIOR_STRENGTH = (
    UNCERTAINTY_CALIBRATION_DEFAULT_A_OBS_PENALTY
)
UNCERTAINTY_CALIBRATION_WIS_SCALE_MULTIPLIER = 2.0
UNCERTAINTY_CALIBRATION_SCORE_PSTATE_DECILES = 10
UNCERTAINTY_CALIBRATION_SCORE_SD_DECILES = UNCERTAINTY_CALIBRATION_SCORE_PSTATE_DECILES
UNCERTAINTY_CALIBRATION_SCORE_STATE_ABS_QUANTILE = 0.90
UNCERTAINTY_CALIBRATION_SCORE_FOLD_CODE_STRIDE = 4096
UNCERTAINTY_CALIBRATION_SCORE_REPLICATE_CODE_STRIDE = 32
UNCERTAINTY_CALIBRATION_SUMMARY_MEDIAN_QUANTILE = 0.50
UNCERTAINTY_CALIBRATION_SUMMARY_Q90_QUANTILE = 0.90
UNCERTAINTY_CALIBRATION_DEFAULT_MAX_SCORES = 200_000
UNCERTAINTY_CALIBRATION_DEFAULT_MAX_DIAGNOSTIC_ROWS = 50_000
UNCERTAINTY_CALIBRATION_DEFAULT_MIN_HELDOUT_CELLS = 1_000
UNCERTAINTY_CALIBRATION_DEFAULT_SEED = 1729
UNCERTAINTY_CALIBRATION_DIAGNOSTIC_SEED_OFFSET = 10_000
UNCERTAINTY_CALIBRATION_MASKED_OBSERVATION_VARIANCE = _float32(1.0e30)

PROCESS_NOISE_DEFAULT_REGULARIZATION_STRENGTH = 1.0
PROCESS_NOISE_DEFAULT_REGULARIZATION_RATIO = 1.0e-4
PROCESS_NOISE_DEFAULT_WARMUP_ECM_ITERS = 25
PROCESS_NOISE_DEFAULT_WARMUP_OUTER_PASSES = 5
PROCESS_NOISE_NUMERICAL_FLOOR = 1.0e-10
UNCERTAINTY_CALIBRATION_REFIT_PROCESS_NOISE_WARMUP_ECM_ITERS = (
    PROCESS_NOISE_DEFAULT_WARMUP_ECM_ITERS
)

STATE_MODEL_LEVEL = "level"
STATE_MODEL_LEVEL_TREND = "levelTrend"
STATE_MODEL_MODES = (
    STATE_MODEL_LEVEL,
    STATE_MODEL_LEVEL_TREND,
)

EXPERIMENT_DEFAULT_NAME = "consenrichExperiment"

INPUT_DEFAULT_SAMPLES = None
INPUT_DEFAULT_BAM_FILES = ()
INPUT_DEFAULT_BAM_FILES_CONTROL = ()
INPUT_DEFAULT_ROLE = "treatment"

OUTPUT_DEFAULT_ROUND_DIGITS = 3
OUTPUT_DEFAULT_WRITE_UNCERTAINTY = True

GENOME_DEFAULT_NAME = None
GENOME_DEFAULT_CHROM_SIZES_FILE = None
GENOME_DEFAULT_BLACKLIST_FILE = None
GENOME_DEFAULT_SPARSE_BED_FILE = None
GENOME_DEFAULT_CHROMOSOMES = None
GENOME_DEFAULT_EXCLUDE_CHROMS = ()
GENOME_DEFAULT_EXCLUDE_FOR_NORM = ()

STATE_DEFAULT_INIT = 0.0
STATE_DEFAULT_COVAR_INIT = 1000.0
STATE_DEFAULT_BOUND_STATE = False
STATE_DEFAULT_LOWER_BOUND = 0.0
STATE_DEFAULT_UPPER_BOUND = 10000.0

COUNTING_DEFAULT_INTERVAL_SIZE_BP = 25
COUNTING_DEFAULT_BACKGROUND_BLOCK_SIZE_BP = -1
COUNTING_DEFAULT_SCALE_FACTORS = None
COUNTING_DEFAULT_SCALE_FACTORS_CONTROL = None
COUNTING_DEFAULT_NORM_METHOD = "EGS"
COUNTING_DEFAULT_FRAGMENTS_GROUP_NORM = "NONE"
COUNTING_SUPPORTED_NORM_METHODS = ("EGS", "RPGC", "RPKM", "CPM", "SF")
COUNTING_SUPPORTED_FRAGMENTS_GROUP_NORMS = ("NONE", "CELLS")
COUNTING_DEFAULT_FIX_CONTROL = False
COUNTING_DEFAULT_LOG_OFFSET = 1.0
COUNTING_DEFAULT_LOG_MULT = 1.0
COUNTING_DEFAULT_REPLICATE_MEDIAN_DETREND = True
COUNTING_DEFAULT_REPLICATE_MEDIAN_DETREND_WINDOW_MULTIPLIER = 5.0
COUNTING_DEFAULT_GENTLE_DETREND_QUANTILE = 0.5

SC_DEFAULT_BARCODE_TAG = "CB"
SC_DEFAULT_COUNT_MODE = "coverage"
SC_DEFAULT_FRAGMENTS_GROUP_NORM = COUNTING_DEFAULT_FRAGMENTS_GROUP_NORM
SC_DEFAULT_FRAGMENT_POSITION_MODE = "insertionEndpoints"
SC_SUPPORTED_COUNT_MODES = SUPPORTED_COUNT_MODES + ("midpoint",)

PROCESS_DEFAULT_DELTA_F = 1.0
PROCESS_DEFAULT_MIN_Q = 1.0e-4
PROCESS_DEFAULT_MAX_Q = 1000.0
PROCESS_DEFAULT_PRECISION_MULTIPLIER_MIN = 0.5
PROCESS_DEFAULT_PRECISION_MULTIPLIER_MAX = 2.0
PROCESS_DEFAULT_STATE_MODEL = STATE_MODEL_LEVEL_TREND

OBSERVATION_DEFAULT_MIN_R = -1.0
OBSERVATION_DEFAULT_MAX_R = 1000.0
OBSERVATION_DEFAULT_SAMPLING_ITERS = 10_000
OBSERVATION_DEFAULT_SAMPLING_BLOCK_SIZE_BP = -1
OBSERVATION_DEFAULT_EB_USE = True
OBSERVATION_DEFAULT_EB_SET_NU0 = None
OBSERVATION_DEFAULT_EB_SET_NUL = None
OBSERVATION_DEFAULT_TREND_NUM_BASIS = 100
OBSERVATION_DEFAULT_TREND_MIN_OBS_PER_BASIS = 25.0
OBSERVATION_DEFAULT_TREND_MIN_EDF = 3.0
OBSERVATION_DEFAULT_TREND_MAX_EDF = 30.0
OBSERVATION_DEFAULT_TREND_LAMBDA_MIN = 1.0e-6
OBSERVATION_DEFAULT_TREND_LAMBDA_MAX = 1.0e6
OBSERVATION_DEFAULT_TREND_LAMBDA_GRID_SIZE = 41
OBSERVATION_DEFAULT_NUM_NEAREST = 0
OBSERVATION_DEFAULT_RESTRICT_LOCAL_AR1_TO_SPARSE_BED = False
OBSERVATION_DEFAULT_SPARSE_SUPPORT_SCALE_BP = -1.0
OBSERVATION_DEFAULT_SPARSE_SUPPORT_PRIOR = 1.0
OBSERVATION_DEFAULT_PAD = 1.0e-3
OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MIN = 1.0
OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MAX = 1.0
OBSERVATION_DEFAULT_USE_REPLICATE_TRENDS = False

FIT_DEFAULT_FIXED_BACKGROUND_ITERS = 50
FIT_DEFAULT_FIXED_BACKGROUND_RTOL = 1.0e-6
FIT_DEFAULT_ROBUST_T_NU = 10.0
FIT_DEFAULT_USE_OBS_PRECISION_REWEIGHTING = False
FIT_DEFAULT_USE_PROCESS_PRECISION_REWEIGHTING = True
FIT_DEFAULT_USE_APN = False
FIT_DEFAULT_BACKGROUND = True
FIT_DEFAULT_ZERO_CENTER_BACKGROUND = False
FIT_DEFAULT_ZERO_CENTER_REPLICATE_BIAS = True
FIT_DEFAULT_OUTER_ITERS = 32
FIT_DEFAULT_MIN_OUTER_ITERS = 2.0
FIT_DEFAULT_BACKGROUND_SHIFT_RTOL = 1.0e-6
FIT_DEFAULT_OUTER_NLL_RTOL = 1.0e-6
FIT_DEFAULT_BACKGROUND_SMOOTHNESS = 1.0
FIT_DEFAULT_BACKGROUND_LENGTH_SCALE_MULTIPLIER = 8.0

SAM_DEFAULT_THREADS = 2
SAM_DEFAULT_FLAG_EXCLUDE = 3844
SAM_DEFAULT_MIN_MAPPING_QUALITY = 10
SAM_DEFAULT_ONE_READ_PER_BIN = 0
SAM_DEFAULT_CHUNK_SIZE = 500_000
SAM_DEFAULT_BAM_INPUT_MODE = "auto"
SAM_DEFAULT_COUNT_MODE = "coverage"
SAM_DEFAULT_SHIFT_FORWARD_5P = 0
SAM_DEFAULT_SHIFT_REVERSE_5P = 0
SAM_DEFAULT_EXTEND_FROM_5P_BP = None
SAM_DEFAULT_MAX_INSERT_SIZE = 1000
SAM_DEFAULT_INFER_FRAGMENT_LENGTH = None
SAM_DEFAULT_MIN_TEMPLATE_LENGTH = -1

MATCHING_DEFAULT_ENABLED = True
MATCHING_DEFAULT_RAND_SEED = 42
MATCHING_DEFAULT_TAU0 = 1.0
MATCHING_DEFAULT_NUM_BOOTSTRAP = 128
MATCHING_DEFAULT_THRESHOLD_Z = 2.0
MATCHING_DEFAULT_DEPENDENCE_SPAN = None
MATCHING_DEFAULT_GAMMA = 0.25
MATCHING_DEFAULT_SELECTION_PENALTY = None
MATCHING_DEFAULT_GAMMA_SCALE = 0.5
MATCHING_DEFAULT_NESTED_ROCCO_ITERS = 3
MATCHING_DEFAULT_NESTED_ROCCO_BUDGET_SCALE = 0.5
MATCHING_DEFAULT_EXPORT_FILTER_UNCERTAINTY_MULTIPLIER = 2.0

UNCERTAINTY_CALIBRATION_DEFAULT_ENABLED = True
UNCERTAINTY_CALIBRATION_DEFAULT_FOLDS = 3
UNCERTAINTY_CALIBRATION_DEFAULT_BLOCK_SIZE_BP = None
UNCERTAINTY_CALIBRATION_DEFAULT_HOLDOUT_FRACTION = None
UNCERTAINTY_CALIBRATION_DEFAULT_HELDOUT_REPLICATE_FRACTION = None
UNCERTAINTY_CALIBRATION_DEFAULT_MAX_HELDOUT_CELLS = None
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MIN_OVERRIDE = None
UNCERTAINTY_CALIBRATION_DEFAULT_FACTOR_MAX_OVERRIDE = None
UNCERTAINTY_CALIBRATION_DEFAULT_A_OBS_PRIOR_STRENGTH_OVERRIDE = None
UNCERTAINTY_CALIBRATION_DEFAULT_CALIBRATION_ECM_ITERS = 3
UNCERTAINTY_CALIBRATION_DEFAULT_TARGET_CALIBRATION_DELTA = 0.05
UNCERTAINTY_CALIBRATION_DEFAULT_SCALE_UNCERTAINTY_BY_TARGET_CALIBRATION = True
UNCERTAINTY_CALIBRATION_DEFAULT_PAD = 1.0e-4
UNCERTAINTY_CALIBRATION_DEFAULT_WRITE_DIAGNOSTICS = False

ROCCO_BUDGET_MIN = 0.001
ROCCO_BUDGET_MAX = 0.10
ROCCO_NULL_QUANTILE = 0.80
ROCCO_THRESHOLD_Z_DEFAULT = MATCHING_DEFAULT_THRESHOLD_Z
ROCCO_NUM_BOOTSTRAP_DEFAULT = MATCHING_DEFAULT_NUM_BOOTSTRAP
ROCCO_BUDGET_Z_GRID = (1.5, 2.0, 2.5, 3.0)
ROCCO_MAX_ITER_DEFAULT = 60
NESTED_ROCCO_ITERS_DEFAULT = MATCHING_DEFAULT_NESTED_ROCCO_ITERS
NESTED_ROCCO_JACCARD_DEFAULT = 0.999
NESTED_ROCCO_MIN_PARENT_STEPS = 5
NESTED_ROCCO_MIN_CHILD_STEPS = NESTED_ROCCO_MIN_PARENT_STEPS
NESTED_ROCCO_BUDGET_SCALE_DEFAULT = MATCHING_DEFAULT_NESTED_ROCCO_BUDGET_SCALE
NESTED_ROCCO_SUBTASK_MAX_ITER = 5
EXPORT_MEDIAN_SIGNAL_LOCAL_UNCERTAINTY_MULTIPLIER = (
    MATCHING_DEFAULT_EXPORT_FILTER_UNCERTAINTY_MULTIPLIER
)
MASSIVE_SUBPEAK_CLEANUP_DEFAULT = True
MASSIVE_SUBPEAK_MIN_BP = 10000
MASSIVE_SUBPEAK_WIDTH_ALPHA = 0.1
MASSIVE_SUBPEAK_WIDTH_BULK_QUANTILE = 0.95
MASSIVE_SUBPEAK_MAX_FRACTION = 0.005
MASSIVE_SUBPEAK_MIN_LOG_GAP = 0.10
MASSIVE_SUBPEAK_MIN_PEAKS = 50
MASSIVE_SUBPEAK_SPLIT_QUANTILE = 0.25
MASSIVE_SUBPEAK_SPLIT_Z = 2.0
MASSIVE_SUBPEAK_MAX_DEPTH = 8
MASSIVE_SUBPEAK_MIN_CHILD_BP = 1000
MASSIVE_SUBPEAK_MIN_CHILD_FRACTION = 0.05

DEFAULT_CONFIGURATION_VALUES: dict[str, dict[str, object]] = {
    GENERIC_DEFAULT_CONFIGURATION: {
        "fitParams.ECM_fixedBackgroundIters": FIT_DEFAULT_FIXED_BACKGROUND_ITERS,
        "fitParams.ECM_fixedBackgroundRtol": FIT_DEFAULT_FIXED_BACKGROUND_RTOL,
        "fitParams.ECM_outerIters": FIT_DEFAULT_OUTER_ITERS,
        "fitParams.ECM_minOuterIters": FIT_DEFAULT_MIN_OUTER_ITERS,
        "fitParams.ECM_backgroundShiftRtol": FIT_DEFAULT_BACKGROUND_SHIFT_RTOL,
        "fitParams.ECM_outerNLLRtol": FIT_DEFAULT_OUTER_NLL_RTOL,
        "fitParams.ECM_backgroundSmoothness": FIT_DEFAULT_BACKGROUND_SMOOTHNESS,
        "fitParams.ECM_backgroundLengthScaleMultiplier": (
            FIT_DEFAULT_BACKGROUND_LENGTH_SCALE_MULTIPLIER
        ),
        "processParams.regularizationStrength": (
            PROCESS_NOISE_DEFAULT_REGULARIZATION_STRENGTH
        ),
        "processParams.regularizationRatio": PROCESS_NOISE_DEFAULT_REGULARIZATION_RATIO,
        "processParams.processNoiseWarmupECMIters": (
            PROCESS_NOISE_DEFAULT_WARMUP_ECM_ITERS
        ),
        "processParams.stateModel": PROCESS_DEFAULT_STATE_MODEL,
        "processParams.precisionMultiplierMin": (
            PROCESS_DEFAULT_PRECISION_MULTIPLIER_MIN
        ),
        "processParams.precisionMultiplierMax": (
            PROCESS_DEFAULT_PRECISION_MULTIPLIER_MAX
        ),
        "observationParams.precisionMultiplierMin": (
            OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MIN
        ),
        "observationParams.precisionMultiplierMax": (
            OBSERVATION_DEFAULT_PRECISION_MULTIPLIER_MAX
        ),
        "countingParams.gentleDetrendQuantile": (
            COUNTING_DEFAULT_GENTLE_DETREND_QUANTILE
        ),
        "uncertaintyCalibrationParams.enabled": (
            UNCERTAINTY_CALIBRATION_DEFAULT_ENABLED
        ),
    }
}

EFFECTIVE_GENOME_SIZES = {
    "hg19": {
        50: 2685511454,
        75: 2736124898,
        100: 2776919708,
        150: 2827436883,
        200: 2855463800,
        250: 2855044784,
    },
    "hg38": {
        50: 2701495711,
        75: 2747877702,
        100: 2805636231,
        150: 2862010428,
        200: 2887553103,
        250: 2898802627,
    },
    "t2t": {
        50: 2725240337,
        75: 2786136059,
        100: 2814334875,
        150: 2931551487,
        200: 2936403235,
        250: 2960856300,
    },
    "mm10": {
        50: 2308125299,
        75: 2407883243,
        100: 2467481008,
        150: 2494787038,
        200: 2520868989,
        250: 2538590322,
    },
    "mm39": {
        50: 2309746861,
        75: 2410055689,
        100: 2468088461,
        150: 2495461690,
        200: 2521902382,
        250: 2538633971,
    },
    "dm3": {
        50: 130428510,
        75: 135004387,
        100: 139647132,
        150: 144307658,
        200: 148523810,
        250: 151901455,
    },
    "dm6": {
        50: 125464678,
        75: 127324557,
        100: 129789773,
        150: 129940985,
        200: 132508963,
        250: 132900923,
    },
    "ce11": {
        50: 95159402,
        75: 96945370,
        100: 98259898,
        150: 98721103,
        200: 98672558,
        250: 101271756,
    },
}


def resolveGenomeName(genome: str) -> str:
    r"""Standardize the genome name for consistency
    :param genome: Name of the genome. See :class:`consenrich.core.genomeParams`.
    :type genome: str
    :return: Standardized genome name.
    :rtype: str
    :raises ValueError: If the genome is not recognized.
    """
    genome_ = genome.lower()
    if genome_ in ["hg19", "grch37"]:
        return "hg19"
    elif genome_ in ["hg38", "grch38"]:
        return "hg38"
    elif genome_ in ["t2t", "chm13", "t2t-chm13"]:
        return "t2t"
    elif genome_ in ["mm10", "grcm38"]:
        return "mm10"
    elif genome_ in ["mm39", "grcm39"]:
        return "mm39"
    elif genome_ in ["dm3"]:
        return "dm3"
    elif genome_ in ["dm6"]:
        return "dm6"
    elif genome_ in ["ce10", "ws220"]:
        return "ce10"
    elif genome_ in ["ce11", "wbcel235"]:
        return "ce11"
    raise ValueError(
        f"Genome {genome} is not recognized. Please provide a valid genome name or manually specify resources"
    )


def getEffectiveGenomeSize(genome: str, readLength: int) -> int:
    r"""Get the effective genome size for a given genome and read length.

    :param genome: Name of the genome. See :func:`consenrich.constants.resolveGenomeName` and :class:`consenrich.core.genomeParams`.
    :type genome: str
    :param readLength: Length of the reads. See :func:`consenrich.core.getReadLength`.
    :type readLength: int
    :raises ValueError: If the genome is not recognized or if the read length is not available for the genome.
    :return: Effective genome size in base pairs.
    :rtype: int
    """

    global EFFECTIVE_GENOME_SIZES
    genome_: str = resolveGenomeName(genome)
    if genome_ in EFFECTIVE_GENOME_SIZES:
        if readLength not in EFFECTIVE_GENOME_SIZES[genome_]:
            nearestReadLength: int = int(
                min(
                    EFFECTIVE_GENOME_SIZES[genome_].keys(),
                    key=lambda x: abs(x - readLength),
                )
            )
            return EFFECTIVE_GENOME_SIZES[genome_][nearestReadLength]
        return EFFECTIVE_GENOME_SIZES[genome_][readLength]
    raise ValueError(f"Defaults not available for {genome}")


def getGenomeResourceFile(genome: str, fileType: str, dir_: str = "data"):
    r"""Get the path to a genome resource file.

    :param genome: the genome assembly. See :func:`consenrich.constants.resolveGenomeName` and :class:`consenrich.core.genomeParams`.
    :type genome: str
    :param fileType: One of 'sizes', 'blacklist', 'sparse'.
    :type fileType: str
    :return: Path to the resource file.
    :rtype: str
    :raises ValueError: If not a sizes, blacklist, or sparse file.
    :raises FileNotFoundError: If the resource file does not exist.
    """
    if fileType.lower() in ["sizes"]:
        fileName = f"{genome}.sizes"
    elif fileType.lower() in ["blacklist"]:
        fileName = f"{genome}_blacklist.bed"
    elif fileType.lower() in ["sparse"]:
        fileName = f"{genome}_sparse.bed"
    filePath = os.path.join(os.path.dirname(__file__), os.path.join(dir_, fileName))
    if not os.path.exists(filePath):
        raise FileNotFoundError(f"Resource file {filePath} does not exist.")
    return filePath
